spring:
  application:
    name: demo
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:6543/postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/postgres
    username: postgres
    password: password
  jpa:
    database: default
second:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:7654/postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7654/postgres
    username: postgres
    password: another






